In [7]:
from sklearn.datasets import fetch_openml

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

import numpy as np
from sklearn.metrics import multilabel_confusion_matrix
import matplotlib.pyplot as plt
from sklearn.metrics import recall_score
from joblib import dump, load

In [8]:
mnist = fetch_openml('mnist_784', version=1)
X, y = mnist['data'], np.array([int(i) for i in mnist['target']])
X_train, X_test, y_train, y_test = X[:60000], X[60000:], y[:60000], y[60000:]
shuffle_index = np.random.permutation(60000)
X_train_shf, y_train_shf = X_train[shuffle_index], y_train[shuffle_index]

In [10]:
from sklearn.base import BaseEstimator

class MyEstimator (BaseEstimator):
    def __init__(self, model, model_params={}):
        self.models = np.array([])
        for i in range(10):
            self.models = np.append(self.models, [model(**model_params)])
        
    def fit(self, X, y):
        ys = np.array([], dtype=bool)
        for i in range(10):
            ys = np.append(ys, [True if a == i else False for a in y ])
        ys = ys.reshape(-1, 10, order='F')
        
        for i in range(10):
            self.models[i].fit(X, ys[:, i])            
            
    def predict(self, X):
        ys = np.array([])
        yresult = np.array([])
        for i in range(10):
            ys = np.append(ys, (self.models[i].predict_proba(X))[:,1])
        ys = ys.reshape(-1, 10, order='F')
        for j in range(len(ys)):
            yresult = np.append(yresult,np.where(ys[j] == np.amax(ys[j]))[0][0])
            
        return  yresult
    

In [11]:
model = MyEstimator(LogisticRegression , {'max_iter':70} )

In [12]:
model.fit(X_train_shf,y_train_shf
         )

/home/tina/Documents/MLStuff/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/tina/Documents/MLStuff/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#l

In [13]:
Yp= model.predict(X_test)

In [14]:
Yp

array([7., 2., 1., ..., 4., 5., 6.])

In [4]:
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score 
from sklearn.metrics import accuracy_score


In [16]:
accuracy_score(y_test , Yp)

0.9186

In [21]:

precision_score(y_test , Yp , average=None)

array([0.95029821, 0.96210164, 0.93188854, 0.89756098, 0.92510121,
       0.90487515, 0.93627955, 0.9302554 , 0.84070796, 0.9001996 ])

In [24]:
logMode = LogisticRegression(max_iter=70)
logMode.fit(X_train_shf , y_train_shf)

/home/tina/Documents/MLStuff/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=70)

In [26]:
Ypp = logMode.predict(X_test)

In [28]:
precision_score(y_test ,Ypp , average=None)

array([0.95704296, 0.96698523, 0.93065327, 0.90224829, 0.93258427,
       0.89430894, 0.93911249, 0.93248532, 0.86754297, 0.90891089])

In [30]:

np.mean(precision_score(y_test ,Ypp , average=None))

0.9231874629491801

In [32]:
np.mean(precision_score(y_test ,Yp , average=None))

0.9179268246905707